@startuml
left to right direction

actor Utilisateur

rectangle "Système décisionnel" {

  Utilisateur --> (Choisir source de données)

  (Choisir source de données) --> (Sélectionner Odoo)
  (Choisir source de données) --> (Sélectionner Northwind)

  (Choisir application business) .> (Choisir source de données) : <<include>>

  (Choisir application business) --> (Sales)
  (Choisir application business) --> (Accounting)
  (Choisir application business) --> (CRM)

  Utilisateur --> (Consulter dashboard)
  Utilisateur --> (Poser une question au chatbot IA)

  (Consulter dashboard) .> (Choisir application business) : <<include>>
  (Poser une question au chatbot IA) .> (Choisir application business) : <<include>>

}

@enduml